language: node_js
node_js: stable
cache: 
  directories: node_modules
install: npm install
services: postgresql
before_script:
  - psql -c "CREATE DATABASE weatherDB;" -U postgres
  - psql -c "CREATE USER okpo WITH PASSWORD 'vict123';" -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: npm test
after_success: npm run coverage
env:
  global:
    - CC_TEST_REPORTER_ID=9d541cd9a01118cd71c4211c22b555c8bdf91049e232dd2f8d892221bcbb14e1
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  addons:
  hosts:
    - 127.0.0.1 
  